import { CardProps } from './components/card/Card';

export const dataCards: CardProps[] = [
  {
    id: 1,
    src: './src/assets/img/1.webp',
    title: 'maqi LAVA COOKIES',
    author: 'ka Lok Hong',
    likes: 199,
    show: 2000,
  },
  {
    id: 2,
    src: './src/assets/img/2.webp',
    title: 'Collection 2020',
    author: 'SATISH GANGAIAH',
    likes: 380,
    show: 4700,
  },
  {
    id: 3,
    src: './src/assets/img/3.webp',
    title: "'Trobada' Wall, Cantonigròs (Catalonia)",
    author: 'Reskate Studio',
    likes: 102,
    show: 748,
  },
  {
    id: 4,
    src: './src/assets/img/4.webp',
    title: 'Anton Muhin PH & Sasha',
    author: 'anga make up',
    likes: 38,
    show: 414,
  },
  {
    id: 5,
    src: './src/assets/img/5.webp',
    title: 'KLM - Up For It',
    author: 'Woodwork Amsterdam',
    likes: 538,
    show: 5300,
  },
  {
    id: 6,
    src: './src/assets/img/6.webp',
    title: 'Voice recorder',
    author: 'Layo Studio',
    likes: 739,
    show: 7700,
  },
  {
    id: 7,
    src: './src/assets/img/7.webp',
    title: 'Collection Character vol1',
    author: 'Yossef Salama',
    likes: 223,
    show: 1300,
  },
  {
    id: 8,
    src: './src/assets/img/8.webp',
    title: 'A Night At The Opera for Tatler UK',
    author: 'Velweiss Retouch',
    likes: 74,
    show: 654,
  },
  {
    id: 9,
    src: './src/assets/img/9.webp',
    title: 'The Face Art Academy',
    author: 'Egle Ruibyte',
    likes: 478,
    show: 610,
  },
  {
    id: 10,
    src: './src/assets/img/10.webp',
    title: 'Winds of Change',
    author: 'Allan Peters',
    likes: 387,
    show: 3200,
  },
  {
    id: 11,
    src: './src/assets/img/11.webp',
    title: 'Jaime Hayde Artbook',
    author: 'Jaime Hayde',
    likes: 337,
    show: 3200,
  },
  {
    id: 12,
    src: './src/assets/img/12.webp',
    title: 'Porsche at Night',
    author: 'GF Williams',
    likes: 160,
    show: 2000,
  },
  {
    id: 13,
    src: './src/assets/img/13.webp',
    title: 'Niwaki Catalogue',
    author: 'Sophie Chatellier',
    likes: 168,
    show: 2000,
  },
  {
    id: 14,
    src: './src/assets/img/14.webp',
    title: 'TYPE 0.7',
    author: 'Huston Wilson',
    likes: 484,
    show: 3000,
  },
  {
    id: 15,
    src: './src/assets/img/15.webp',
    title: 'Festival Packaging for WAGAS',
    author: 'Inkee Wang',
    likes: 730,
    show: 5000,
  },
  {
    id: 16,
    src: './src/assets/img/16.webp',
    title: 'MAMA',
    author: 'FAENA Studio',
    likes: 425,
    show: 2900,
  },
  {
    id: 17,
    src: './src/assets/img/17.webp',
    title: 'XKR_002 | Protect',
    author: 'XK stydio',
    likes: 542,
    show: 2800,
  },
  {
    id: 18,
    src: './src/assets/img/18.webp',
    title: 'Mooah #003',
    author: 'Hanee O',
    likes: 135,
    show: 1100,
  },
  {
    id: 19,
    src: './src/assets/img/19.webp',
    title: 'peep coffee',
    author: 'Hui Tong',
    likes: 5400,
    show: 47700,
  },
  {
    id: 20,
    src: './src/assets/img/20.webp',
    title: 'The cozy purrs',
    author: 'Đốm Đốm',
    likes: 5400,
    show: 47700,
  },
];
